// todo-simplified/vue-todo-app/src/components/Navbar.vue
<template>
  <div class="navbar bg-base-100 shadow-sm">
    <div class="navbar-start">
      <a href="#" class="btn btn-ghost text-xl">Vue Todo App</a>
    </div>

    <div class="navbar-end">
      <ThemeToggle />
    </div>
  </div>
</template>

<script setup>
import ThemeToggle from './ThemeToggle.vue';
</script>

// human-resource-management/react-version/src/ui/Navbar.tsx
function Navbar() {
  return (
    <div className="navbar fixed top-0 z-50 bg-white/30 shadow-sm backdrop-blur-md">
      <div className="navbar-start">
        <a className="btn btn-ghost text-xl">daisyUI</a>
      </div>

      <div className="navbar-end">
        <a className="btn">Button</a>
      </div>
    </div>
  );
}

export default Navbar;
